import { useState } from "react";
import Head from "next/head";
import Header from "@/components/Header";
import AppSidebar from "@/components/Sidebar/AppSidebar";
import MainContent from "@/components/MainContent";
import MoreGames from "@/components/Games/MoreGames";
import GalaticMarket from "@/components/GalacticMarket/index";
import HottestGames from "@/components/Games/HottestGames";
import { SectionOne, SectionTwo } from "@/components/Sections";
import { Web3ReactProvider } from "@web3-react/core";
import { Web3Provider } from "@ethersproject/providers";

function getLibrary(provider) {
  const library = new Web3Provider(provider);
  library.pollingInterval = 12000;
  return library;
}

export default function Home() {

  const [isMouseOver, setIsMouseOver] = useState(false);

  return (
    <>
      <Web3ReactProvider getLibrary={getLibrary}>
        <Head>
          <title>Alien Inu</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>

        <main className="flex flex-col min-h-screen">
          <Header />
          <AppSidebar isMouseOver={isMouseOver} setIsMouseOver={setIsMouseOver} />

          {/* Main Content */}
          <MainContent isMouseOver={isMouseOver}>
            {/* Row One */}
            <SectionOne />

            {/* Row Two */}
            <SectionTwo />

            {/* Row tree */}
            <MoreGames />

            {/* Row four */}
            <GalaticMarket />

            {/* Row five */}
            <HottestGames />
          </MainContent>

        </main>
      </Web3ReactProvider>
    </>
  );
}
